<a href="https://colab.research.google.com/github/KiruthikaVM2005/My-project/blob/main/agriculture.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd

In [40]:
df=pd.read_csv('Crop_recommendation.csv')
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [41]:
df.isna().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [43]:
x=df.drop('label',axis=1)
y=df['label']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [44]:
model=RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)

RandomForestClassifier()

In [45]:
predictions=model.predict(x_test)
accuracy=accuracy_score(y_test,predictions)
print(accuracy)

0.9931818181818182

In [46]:
crop_prices={'rice':20, 'maize':18,'banana':30, 'mango':50, 'cotton':60,'coconut':35}
def estimate_yield(crop):
  yield_data={'rice':3000, 'maize':2500,'banana':20000, 'mango':10000, 'cotton':2000,'coconut':10000}
  return yield_data.get(crop,2000)

In [47]:
def calculate_profit(crop):
  price=crop_prices.get(crop,20)
  yield_amt=estimate_yield(crop)
  profit=price*yield_amt
  return profit

In [48]:
region_data = {
    'Tamil Nadu': {'temperature': 30, 'humidity': 70, 'rainfall': 150},
    'Kerala': {'temperature': 28, 'humidity': 85, 'rainfall': 300},
    'Punjab': {'temperature': 25, 'humidity': 60, 'rainfall': 100}
}

In [49]:
region = input("Enter Region: ")
region_values = region_data.get(region, {'temperature': 25,'humidity': 60,'rainfall': 100})
N = float(input("Enter Nitrogen: "))
P = float(input("Enter Phosphorus: "))
K = float(input("Enter Potassium: "))
ph = float(input("Enter pH: "))
temperature = input("Enter Temperature (press Enter to use region value): ")
humidity = input("Enter Humidity (press Enter to use region value): ")
rainfall = input("Enter Rainfall (press Enter to use region value): ")
temperature = float(temperature) if temperature else region_values['temperature']
humidity = float(humidity) if humidity else region_values['humidity']
rainfall = float(rainfall) if rainfall else region_values['rainfall']
user_data = pd.DataFrame([[N, P, K, temperature, humidity, ph, rainfall]],
                         columns=['N','P','K','temperature','humidity','ph','rainfall'])
probs = model.predict_proba(user_data)[0]

top3_idx = probs.argsort()[-3:][::-1]
top3_crops = model.classes_[top3_idx]

print("\nTop 3 Crops:\n")

for crop in top3_crops:
    profit = calculate_profit(crop)
    print("Crop:", crop)
    print("Estimated Profit:", profit)
    print("------")

Enter Region: Kerala
Enter Nitrogen: 45
Enter Phosphorus: 5
Enter Potassium: 35
Enter pH: 7.5
Enter Temperature (press Enter to use region value):
Enter Humidity (press Enter to use region value):
Enter Rainfall (press Enter to use region value):

Top 3 Crops:

Crop: coconut
Estimated Profit: 350000
------
Crop: pomegranate
Estimated Profit: 40000
------
Crop: mungbean
Estimated Profit: 40000
------

In [51]:
!pip install tensorflow keras

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (3.13.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras) (0.19.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.2)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)

In [53]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2,preprocess_input,decode_predictions
from google.colab import files

In [66]:
model=MobileNetV2(weights='imagenet')
uploaded=files.upload()
img_path=list(uploaded.keys())[0]
img=image.load_img(img_path,target_size=(224,224))
img_array = image.img_to_array(img)
img_array=np.expand_dims(img_array,axis=0)
img_array=preprocess_input(img_array)
predictions=model.predict(img_array)
decoded=decode_predictions(predictions)
import random
diseases = ['Bacterial Blight', 'Leaf Spot', 'Rust', 'Healthy']
print("\nPredicted Disease:", random.choice(diseases))

Saving leaf disease.jpg to leaf disease (3).jpg
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step

Predicted Disease: Leaf Spot